--- 

  - name: update cache
    yum:
      update_cache: yes
      state: present 


  - name: install yum-utils
    yum:
      name: yum-utils
      state: present
    

  - name: Add docker repository
    yum_repository:
      name: docker
      file: docker
      description: docker YUM repo
      baseurl: "{{ docker_redhat_repo.url }}"

 
  - name: install docker packages
    yum:
      update_cache: yes
      name: "{{ docker_packages }}"
      state: present
